import{suggestPhraseBoundaries}from'./phrase-model.js';
const clamp=(n,lo=0,hi=1)=>Math.max(lo,Math.min(hi,n));
const mod12=n=>((Number(n)%12)+12)%12;
const mode=k=>k?.keyMode||k?.analysis?.keyMode||null;
const root=k=>Number.isInteger(k?.keyRoot)?k.keyRoot:Number.isInteger(k?.analysis?.keyRoot)?k.analysis.keyRoot:null;
const relativeMajor=k=>{const r=root(k),m=mode(k);return r==null?null:mod12(r+(m==='minor'?3:0))};
export function keyRelation(a,b){const ar=root(a),br=root(b),am=mode(a),bm=mode(b),ra=relativeMajor(a),rb=relativeMajor(b);if(ar==null||br==null)return{kind:'unknown',score:.5,distance:null};const d=mod12(rb-ra),semi=Math.min(d,12-d);if(ra===rb)return{kind:am===bm&&ar===br?'same key':'relative key',score:1,distance:0};if(ar===br&&am!==bm)return{kind:'parallel key',score:.78,distance:0};if(d===5||d===7)return{kind:'fifth-related',score:.82,distance:semi};const table=[1,.48,.58,.46,.56,.82,.28],score=table[semi]??.4;return{kind:`${semi}-semitone key distance`,score,distance:semi}}
export function bestKeyShift(a,b,{maxShift=6}={}){let best=null;for(let shift=-maxShift;shift<=maxShift;shift++){const proxy={keyRoot:root(b)==null?null:mod12(root(b)+shift),keyMode:mode(b)},rel=keyRelation(a,proxy),score=rel.score-Math.abs(shift)*.018,cand={shift,relation:rel,score};if(!best||cand.score>best.score+1e-9||Math.abs(cand.score-best.score)<1e-9&&Math.abs(shift)<Math.abs(best.shift))best=cand}return best}
export function tempoCompatibility(aBpm,bBpm){const a=Math.max(1,Number(aBpm)||120),b=Math.max(1,Number(bBpm)||120),ratio=a/b,diff=Math.abs(ratio-1),score=diff<=.04?1:diff<=.1?1-(diff-.04)*4:diff<=.2?.76-(diff-.1)*3:.46*Math.exp(-(diff-.2)*2);return{ratio,percent:(ratio-1)*100,score:clamp(score)}}
export function meterCompatibility(a,b){const av=Number(a?.beatsPerBar??a?.analysis?.beatsPerBar??4),bv=Number(b?.beatsPerBar??b?.analysis?.beatsPerBar??4);if(av===bv)return{kind:'same meter',score:1};if(new Set([av,bv]).has(3)&&new Set([av,bv]).has(6))return{kind:'3/4 ↔ 6/8 compound relation',score:.65};return{kind:'different meter',score:.35}}
export function mashupCompatibility(a,b){const key=keyRelation(a.analysis||a,b.analysis||b),keyShift=bestKeyShift(a.analysis||a,b.analysis||b),tempo=tempoCompatibility(a.sourceBpm||a.analysis?.bpm,b.sourceBpm||b.analysis?.bpm),meter=meterCompatibility(a,b),score=clamp(key.score*.5+tempo.score*.3+meter.score*.2);return{score,key,keyShift,tempo,meter}}
export function suggestAlignmentPairs(a,b,{maxPairs=5}={}){const as=suggestPhraseBoundaries(a),bs=suggestPhraseBoundaries(b);if(!as.length||!bs.length)return[];const out=[];for(const x of as)for(const y of bs){const xa=x.bar-1,ya=y.bar-1,struct=xa%32===ya%32?.22:xa%16===ya%16?.16:xa%8===ya%8?.1:xa%4===ya%4?.04:0,confidence=(x.confidence+y.confidence)/2,earlyPenalty=Math.min(.12,(x.bar+y.bar)*.0015),score=clamp(confidence*.78+struct-earlyPenalty);out.push({a:x,b:y,score,confidence,structural:struct})}return out.sort((x,y)=>y.score-x.score).slice(0,maxPairs)}
