import{state,$,markDirty}from'./state.js';
import{stopAudio}from'./audio.js';
import{projectDiagnostics,diagnosticSeverity}from'./diagnostics.js';
import{STEM_TYPES,ensureStemState}from'./stems.js';
import{trackHasDspEdits}from'./render.js';

const SESSION_KEY='echoverse.phase.session.v5',ENDPOINT_KEY='echoverse.phase.stemEndpoint',MB=1024*1024;
let lastReport=null;
const style=document.createElement('style');style.textContent=`
.diag-drawer{position:fixed;z-index:75;top:82px;left:12px;width:min(560px,calc(100vw - 24px));max-height:calc(100vh - 110px);overflow:auto;border:1px solid #2a3945;border-radius:8px;background:#0d1319;box-shadow:0 18px 50px rgba(0,0,0,.48);padding:10px;display:none}.diag-drawer.open{display:block}
.diag-head{display:flex;align-items:center;gap:7px;margin-bottom:8px}.diag-head strong{font:700 11px ui-monospace,monospace;letter-spacing:.08em}.diag-head .spacer{flex:1}.diag-badge{font:700 8px ui-monospace,monospace;padding:3px 6px;border-radius:999px;border:1px solid #334451;color:#9eabb4}.diag-badge.ok{border-color:#3f756b;color:#9fd2c9}.diag-badge.warning{border-color:#806b3e;color:#d8c28f}.diag-badge.error{border-color:#7a4545;color:#d89f9f}
.diag-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.diag-card{border:1px solid #202d36;border-radius:6px;background:#10171d;padding:8px;min-width:0}.diag-card h4{margin:0 0 6px;font:700 9px ui-monospace,monospace;color:#aab7be}.diag-kv{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:3px 8px;font:8px/1.45 ui-monospace,monospace}.diag-kv span:nth-child(odd){color:#75858f}.diag-kv span:nth-child(even){color:#c3ced4;text-align:right;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.diag-warning{margin-top:6px;padding:5px 6px;border-left:2px solid #806b3e;background:#17150f;color:#c9b27e;font:8px/1.45 ui-monospace,monospace;word-break:break-word}.diag-warning.error{border-color:#7a4545;background:#1a1111;color:#d5a0a0}.diag-actions{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px;padding-top:8px;border-top:1px solid #202d36}.diag-note{margin-top:7px;font:8px/1.45 ui-monospace,monospace;color:#71818b}.diag-btn-active{border-color:#66b5a8!important;background:#1d302d!important;color:#d8eee8!important}
@media(max-width:700px){.diag-drawer{top:112px;left:7px;width:calc(100vw - 14px);max-height:calc(100vh - 140px)}.diag-grid{grid-template-columns:1fr}}
`;
document.head.appendChild(style);

const fmtBytes=n=>{const v=Number(n)||0;if(v<1024)return`${v} B`;if(v<1048576)return`${(v/1024).toFixed(1)} KB`;if(v<1073741824)return`${(v/1048576).toFixed(1)} MB`;return`${(v/1073741824).toFixed(2)} GB`};
const yes=v=>v?'YES':'NO';
function appVersion(){return($('.brand .tag')?.textContent||$('.footer span')?.textContent||'').replace(/ALPHA|PHASE/gi,'').trim()}
async function environment(){
  const deviceMemory=Number(navigator.deviceMemory)||null,env={version:appVersion(),secureContext:!!window.isSecureContext,online:navigator.onLine,webAudio:!!(window.AudioContext||window.webkitAudioContext),offlineAudio:!!window.OfflineAudioContext,worker:!!window.Worker,serviceWorker:'serviceWorker'in navigator,crossOriginIsolated:!!window.crossOriginIsolated,location:location.origin+location.pathname,hardwareConcurrency:Number(navigator.hardwareConcurrency)||null,deviceMemoryGB:deviceMemory,audioMemoryWarnBytes:(deviceMemory&&deviceMemory<=4?384:deviceMemory&&deviceMemory>=8?768:512)*MB};
  try{const estimate=await navigator.storage?.estimate?.();if(estimate){env.storageUsage=estimate.usage||0;env.storageQuota=estimate.quota||0}}catch{}
  try{const pm=performance?.memory;if(pm){env.jsHeapUsed=pm.usedJSHeapSize||0;env.jsHeapTotal=pm.totalJSHeapSize||0;env.jsHeapLimit=pm.jsHeapSizeLimit||0}}catch{}
  try{const reg=await navigator.serviceWorker?.getRegistration?.();env.serviceWorkerControlled=!!navigator.serviceWorker.controller;env.serviceWorkerState=reg?.active?.state||reg?.installing?.state||reg?.waiting?.state||null}catch{env.serviceWorkerControlled=false}
  try{env.cacheNames='caches'in window?await caches.keys():[]}catch{env.cacheNames=[]}
  try{env.sessionSaved=!!localStorage.getItem(SESSION_KEY);env.separatorConfigured=!!localStorage.getItem(ENDPOINT_KEY)}catch{env.sessionSaved=false;env.separatorConfigured=false}
  return env;
}
function trackCard(t){
  const a=t.analysis||{},stem=t.stems||{},warn=t.warnings||[];
  return`<div class="diag-card"><h4>${t.label} · ${t.loaded?'SOURCE LOADED':'NO SOURCE'}</h4><div class="diag-kv"><span>File</span><span title="${t.fileName||''}">${t.fileName||'—'}</span><span>Audio</span><span>${t.loaded?`${t.duration}s · ${t.sampleRate||'?'} Hz · ${t.channels||'?'} ch`:'—'}</span><span>Audio memory</span><span>${fmtBytes(t.memoryBytes||0)}</span><span>Grid</span><span>${t.gridMode||'—'} · ${t.markers} markers</span><span>Analysis</span><span>${a.bpm?`${a.bpm} BPM · ${a.meter||'?'} · ${a.key||'key ?'}`:'—'}</span><span>Stems</span><span>${stem.loaded?.length?`${stem.enabled?'ON':'LOADED'} · ${stem.loaded.join(', ')}`:'—'}</span><span>Stem solo</span><span>${stem.solo?.length?stem.solo.join(', '):'—'}</span><span>Render</span><span>${t.render.hasRendered?`${t.render.quality||'rendered'}${t.render.reused?' · reused':''}`:'DIRECT / NONE'}</span></div>${warn.map(w=>`<div class="diag-warning${/REVERSED|NOT_INCREASING|WITHOUT_STEMS/.test(w)?' error':''}">${w}</div>`).join('')}</div>`;
}
function render(report){
  lastReport=report;const severity=diagnosticSeverity(report),badge=$('#diagBadge');badge.className=`diag-badge ${severity}`;badge.textContent=severity==='ok'?'HEALTHY':severity==='warning'?`${report.warnings.length} WARNING${report.warnings.length===1?'':'S'}`:'ATTENTION';
  const e=report.environment,p=report.project,storage=e.storageQuota?`${fmtBytes(e.storageUsage)} / ${fmtBytes(e.storageQuota)}`:'UNKNOWN',heap=e.jsHeapLimit?`${fmtBytes(e.jsHeapUsed)} / ${fmtBytes(e.jsHeapLimit)}`:'NOT EXPOSED';
  $('#diagBody').innerHTML=`<div class="diag-grid"><div class="diag-card"><h4>RUNTIME</h4><div class="diag-kv"><span>Version</span><span>${report.version||'—'}</span><span>HTTPS / secure</span><span>${yes(e.secureContext)}</span><span>Online</span><span>${yes(e.online)}</span><span>Web Audio</span><span>${yes(e.webAudio)}</span><span>Offline Audio</span><span>${yes(e.offlineAudio)}</span><span>Web Worker</span><span>${yes(e.worker)}</span><span>CPU threads</span><span>${e.hardwareConcurrency||'UNKNOWN'}</span><span>Device memory</span><span>${e.deviceMemoryGB?`${e.deviceMemoryGB} GB`:'NOT EXPOSED'}</span><span>JS heap</span><span>${heap}</span><span>Cross-origin isolated</span><span>${yes(e.crossOriginIsolated)}</span></div></div><div class="diag-card"><h4>PWA / STORAGE</h4><div class="diag-kv"><span>Service worker</span><span>${e.serviceWorkerState||'NONE'}</span><span>Controls page</span><span>${yes(e.serviceWorkerControlled)}</span><span>App caches</span><span>${e.cacheNames?.length||0}</span><span>Storage</span><span>${storage}</span><span>Session map</span><span>${e.sessionSaved?'SAVED':'NONE'}</span><span>Separator</span><span>${e.separatorConfigured?'CONFIGURED':'NOT SET'}</span></div></div><div class="diag-card"><h4>PROJECT</h4><div class="diag-kv"><span>Tempo</span><span>${p.bpm} BPM</span><span>Meter</span><span>${p.meter}</span><span>Visual edits</span><span>${p.dirty?'PENDING':'CURRENT'}</span><span>Render</span><span>${p.rendering?'RUNNING':'IDLE'}</span><span>Playback</span><span>${p.playing?'PLAYING':'STOPPED'}</span><span>Decoded audio</span><span>${fmtBytes(p.audioMemoryBytes||0)}</span><span>Memory caution</span><span>${fmtBytes(p.memoryWarnBytes||0)}</span><span>View</span><span>${p.viewDuration}s · ${p.zoomPxPerSecond}px/s</span></div></div>${report.tracks.map(trackCard).join('')}</div>${report.warnings.length?`<div class="diag-warning${severity==='error'?' error':''}">${report.warnings.join(' · ')}</div>`:'<div class="diag-note">No project/runtime warnings detected by the current diagnostic checks.</div>'}`;
}
async function run(){const btn=$('#diagRun');if(btn){btn.disabled=true;btn.textContent='CHECKING…'}try{render(projectDiagnostics(state,await environment()))}finally{if(btn){btn.disabled=false;btn.textContent='CHECK AGAIN'}}}
function download(){if(!lastReport)return;const blob=new Blob([JSON.stringify(lastReport,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`phase-diagnostics-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)}
async function copy(){if(!lastReport)return;try{await navigator.clipboard.writeText(JSON.stringify(lastReport,null,2));$('#engineState').textContent='DIAGNOSTICS COPIED'}catch{download();$('#engineState').textContent='CLIPBOARD UNAVAILABLE · REPORT DOWNLOADED'}}
async function updateApp(){const b=$('#diagUpdate');b.disabled=true;b.textContent='UPDATING…';try{const reg=await navigator.serviceWorker?.getRegistration?.();await reg?.update?.();$('#engineState').textContent='APP UPDATE CHECK COMPLETE';await run()}catch(err){console.error(err);$('#engineState').textContent='APP UPDATE CHECK FAILED'}finally{b.disabled=false;b.textContent='CHECK APP UPDATE'}}
async function resetCache(){if(!confirm('Reset Phase app caches and service worker? Your saved project/session map and local source files are not deleted.'))return;stopAudio();$('#engineState').textContent='RESETTING PHASE APP CACHE…';try{if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('echoverse-phase-shell-')).map(k=>caches.delete(k)))}const regs=await navigator.serviceWorker?.getRegistrations?.()||[];await Promise.all(regs.filter(r=>r.scope.startsWith(location.origin)).map(r=>r.unregister()));location.replace(`${location.pathname}?recovery=${Date.now()}`)}catch(err){console.error(err);$('#engineState').textContent='CACHE RESET FAILED';alert('Cache reset failed: '+(err.message||err))}}
function clearRendered(){stopAudio();let changed=false;for(const t of state.tracks){if(t.renderedBuffer||t.renderedSignature){t.renderedBuffer=null;t.renderedSignature=null;t.renderStats=null;changed=true}ensureStemState(t);for(const id of STEM_TYPES){const s=t.stems[id];if(s.renderedBuffer||s.renderedSignature){s.renderedBuffer=null;s.renderedSignature=null;s.renderStats=null;changed=true}}if(trackHasDspEdits(t))markDirty()}$('#engineState').textContent=changed?'RENDER CACHE CLEARED · RENDER CHANGES WHEN READY':'NO RENDER CACHE TO CLEAR';run()}
function install(){
  if(!$('#diagPanel')){const b=document.createElement('button');b.id='diagPanel';b.className='btn';b.textContent='DIAG';b.title='Open Phase diagnostics and recovery';$('#install').after(b);b.onclick=()=>{const d=$('#diagDrawer');d.classList.toggle('open');if(d.classList.contains('open'))run()}}
  if($('#diagDrawer'))return;const d=document.createElement('div');d.id='diagDrawer';d.className='diag-drawer';d.innerHTML=`<div class="diag-head"><strong>PHASE DIAGNOSTICS</strong><span class="diag-badge" id="diagBadge">CHECKING</span><span class="spacer"></span><button class="mini" id="diagClose">CLOSE</button></div><div id="diagBody"></div><div class="diag-actions"><button class="mode" id="diagRun">CHECK AGAIN</button><button class="mode" id="diagUpdate">CHECK APP UPDATE</button><button class="mode" id="diagCopy">COPY REPORT</button><button class="mode" id="diagDownload">DOWNLOAD REPORT</button><button class="mode" id="diagClearRender">CLEAR RENDER CACHE</button><button class="mode" id="diagResetCache">RESET APP CACHE</button></div><div class="diag-note">Decoded-audio memory is estimated from resident Web Audio buffers and is intentionally conservative. RESET APP CACHE removes Phase CacheStorage/service-worker state only; it does not intentionally delete the saved session map.</div>`;document.body.appendChild(d);$('#diagClose').onclick=()=>d.classList.remove('open');$('#diagRun').onclick=run;$('#diagUpdate').onclick=updateApp;$('#diagCopy').onclick=copy;$('#diagDownload').onclick=download;$('#diagClearRender').onclick=clearRendered;$('#diagResetCache').onclick=resetCache;
}
window.addEventListener('phase:project-applied',()=>{$('#diagDrawer')?.classList.contains('open')&&setTimeout(run,0)});window.addEventListener('phase:history-applied',()=>{$('#diagDrawer')?.classList.contains('open')&&setTimeout(run,0)});window.addEventListener('online',()=>$('#diagDrawer')?.classList.contains('open')&&run());window.addEventListener('offline',()=>$('#diagDrawer')?.classList.contains('open')&&run());window.addEventListener('keydown',e=>{if(e.code==='Escape'&&$('#diagDrawer')?.classList.contains('open'))$('#diagDrawer').classList.remove('open')});
install();
