import{state,$}from'./state.js';

const style=document.createElement('style');style.textContent=`
.help-drawer{position:fixed;z-index:74;top:82px;right:12px;width:min(540px,calc(100vw - 24px));max-height:calc(100vh - 110px);overflow:auto;border:1px solid #2a3945;border-radius:8px;background:#0d1319;box-shadow:0 18px 50px rgba(0,0,0,.48);padding:10px;display:none}.help-drawer.open{display:block}
.help-head{display:flex;align-items:center;gap:7px;margin-bottom:8px}.help-head strong{font:700 11px ui-monospace,monospace;letter-spacing:.08em}.help-head .spacer{flex:1}.help-context{font:700 8px ui-monospace,monospace;color:#9fd2c9;border:1px solid #365852;border-radius:999px;padding:3px 6px}
.help-tabs{display:flex;gap:5px;margin-bottom:8px}.help-tabs .active{border-color:#66b5a8;background:#1d302d;color:#d8eee8}.help-section{border:1px solid #202d36;border-radius:6px;background:#10171d;padding:9px;margin-bottom:7px}.help-section h4{margin:0 0 7px;font:700 9px ui-monospace,monospace;color:#b6c2c9}.help-section p{margin:0;color:#82919a;font:9px/1.55 ui-monospace,monospace}.help-flow{display:grid;grid-template-columns:auto 1fr;gap:5px 9px;font:9px/1.45 ui-monospace,monospace}.help-flow b{color:#9fd2c9}.help-flow span{color:#8998a1}.shortcut-grid{display:grid;grid-template-columns:auto 1fr;gap:5px 10px;align-items:center;font:9px/1.4 ui-monospace,monospace}.shortcut-grid kbd{justify-self:start;border:1px solid #344754;border-bottom-color:#506675;border-radius:4px;background:#0c1217;color:#d3dde2;padding:2px 6px;white-space:nowrap}.shortcut-grid span{color:#8998a1}.help-note{font:8px/1.5 ui-monospace,monospace;color:#70808a}
@media(max-width:620px){.help-drawer{top:112px;right:7px;width:calc(100vw - 14px);max-height:calc(100vh - 140px)}}
`;
document.head.appendChild(style);

let tab='quick';
function selectedLabel(){return Number.isInteger(state.selected?.track)?state.tracks[state.selected.track]?.label||'TRACK':state.tracks.find(t=>t.buffer)?.label||'NO TRACK'}
function context(){return`${String(state.mode||'select').toUpperCase()} · ${selectedLabel()}`}
function quick(){return`<div class="help-section"><h4>FASTEST PATH TO A MASHUP</h4><div class="help-flow"><b>1 · LOAD</b><span>Load Track A and B. Phase keeps source audio local.</span><b>2 · ANALYZE</b><span>Confirm BPM, meter, downbeats and key. Use ½ BPM / ×2 BPM or GRID when detection needs correction.</span><b>3 · ALIGN</b><span>Choose meaningful phrase/downbeat markers on A and B, set ALIGN points, then ALIGN B → A. MATCH / SUGGEST PAIR can propose starting points.</span><b>4 · ARRANGE</b><span>MOVE whole tracks, use phrase snap, trim with I/O, select REGION ranges, and add fades/crossfades.</span><b>5 · RENDER</b><span>Timing/pitch edits stay visual until ⚡ RENDER CHANGES. Mix-only edits such as levels, mute/solo, trims and fades remain instant.</span><b>6 · EXPORT</b><span>Export the full WAV or a loop. STEMS can replace either original mix with vocal/drum/bass/other parts.</span></div></div><div class="help-section"><h4>CURRENT CONTEXT · ${context()}</h4><p>${modeHelp()}</p></div><div class="help-section"><h4>SESSION SAFETY</h4><p>SAVE MAP stores edit intent, not audio bytes. RESTORE SESSION brings the map back. RELINK FILES can reconnect remembered source/stem filenames in one pass. DIAG can inspect runtime health and reset only the PWA cache if startup ever gets stuck.</p></div>`}
function modeHelp(){const m=String(state.mode||'select');if(m==='warp')return'WARP changes target timing between the previous locked anchor and the marker you drag. Source audio is untouched until Render Changes.';if(m==='anchor')return'ANCHOR locks or unlocks beat markers. A locked marker protects everything before it from later regional warp edits.';if(m==='grid')return'GRID corrects a detector tick without creating a timing warp. Use it when analysis found the right musical beat but placed the marker slightly wrong.';if(m==='move')return'MOVE repositions the whole track on the shared project timeline. Phrase snap controls how aggressively placement lands on musical boundaries.';if(m==='region')return'REGION selects a reusable project range for looping, fade/crossfade work and focused export. Hold Shift while dragging for free placement.';return'SELECT is the safe inspection mode. Click beat markers to inspect them, Shift-click to redefine Bar 1/downbeat phase, then switch tools only when you want to edit.'}
function shortcuts(){return`<div class="help-section"><h4>EDITING</h4><div class="shortcut-grid"><kbd>W</kbd><span>Warp tool</span><kbd>A</kbd><span>Anchor tool</span><kbd>G</kbd><span>Grid correction tool</span><kbd>M</kbd><span>Move whole track</span><kbd>R</kbd><span>Region selection tool</span><kbd>I</kbd><span>Set IN trim at playhead</span><kbd>O</kbd><span>Set OUT trim at playhead</span><kbd>Shift + click</kbd><span>Redefine Bar 1 / downbeat on a marker</span><kbd>Shift + region drag</kbd><span>Free region selection without snap</span><kbd>Esc</kbd><span>Return toward SELECT / close open drawers</span></div></div><div class="help-section"><h4>TRANSPORT + VIEW</h4><div class="shortcut-grid"><kbd>Space</kbd><span>Play / stop</span><kbd>Home</kbd><span>Return playhead to project start</span><kbd>← / →</kbd><span>Move playhead one project beat</span><kbd>L</kbd><span>Toggle audition loop</span><kbd>+ / −</kbd><span>Zoom timeline</span><kbd>Click / drag ruler</kbd><span>Seek playhead</span></div></div><div class="help-section"><h4>HISTORY + HELP</h4><div class="shortcut-grid"><kbd>Ctrl/Cmd + Z</kbd><span>Undo metadata/edit-map change</span><kbd>Ctrl/Cmd + Shift + Z</kbd><span>Redo</span><kbd>Ctrl/Cmd + Y</kbd><span>Redo</span><kbd>?</kbd><span>Open / close this help panel</span></div></div><div class="help-note">Keyboard shortcuts are ignored while typing in inputs, selects or text areas.</div>`}
function render(){const d=$('#helpBody'),badge=$('#helpContext');if(d)d.innerHTML=tab==='shortcuts'?shortcuts():quick();if(badge)badge.textContent=context();$('#helpQuick')?.classList.toggle('active',tab==='quick');$('#helpKeys')?.classList.toggle('active',tab==='shortcuts')}
function toggle(force){const d=$('#helpDrawer');if(!d)return;const open=force==null?!d.classList.contains('open'):!!force;d.classList.toggle('open',open);if(open)render()}
function install(){
  if(!$('#helpPanel')){const b=document.createElement('button');b.id='helpPanel';b.className='btn';b.textContent='HELP';b.title='Open Phase workflow help and keyboard map';const anchor=$('#diagPanel')||$('#install');anchor.after(b);b.onclick=()=>toggle()}
  if($('#helpDrawer'))return;const d=document.createElement('div');d.id='helpDrawer';d.className='help-drawer';d.innerHTML=`<div class="help-head"><strong>PHASE HELP</strong><span class="help-context" id="helpContext"></span><span class="spacer"></span><button class="mini" id="helpClose">CLOSE</button></div><div class="help-tabs"><button class="mode active" id="helpQuick">QUICK START</button><button class="mode" id="helpKeys">KEYBOARD MAP</button></div><div id="helpBody"></div>`;document.body.appendChild(d);$('#helpClose').onclick=()=>toggle(false);$('#helpQuick').onclick=()=>{tab='quick';render()};$('#helpKeys').onclick=()=>{tab='shortcuts';render()};render()
}
window.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;if(e.key==='?'||e.code==='Slash'&&e.shiftKey){e.preventDefault();toggle();return}if(e.code==='Escape'&&$('#helpDrawer')?.classList.contains('open'))toggle(false)});
window.addEventListener('phase:project-applied',()=>$('#helpDrawer')?.classList.contains('open')&&render());window.addEventListener('phase:history-applied',()=>$('#helpDrawer')?.classList.contains('open')&&render());
install();
