export function makeTrack(id,label){return{id,label,name:label,buffer:null,renderedBuffer:null,renderedAt:null,peaks:null,duration:0,sourceBpm:120,pitch:0,markers:[],file:null,analysis:null,gridMode:'manual',timelineOffset:0,renderedOffset:0,meterPreference:'auto',meter:'4/4',beatsPerBar:4}}
export const state={mode:'select',bpm:120,meterPreference:'auto',meter:'4/4',beatsPerBar:4,dirty:false,previewCurrent:false,previewRendering:false,dirtyRevision:0,playing:false,audioCtx:null,sources:[],selected:null,showBeats:true,showDownbeats:true,installPrompt:null,rendering:false,viewDuration:60,pxPerSecond:8,tracks:[makeTrack(0,'TRACK A'),makeTrack(1,'TRACK B')]};
export const $=s=>document.querySelector(s);
export const $$=s=>[...document.querySelectorAll(s)];
export function fmt(t){if(!Number.isFinite(t))return'—';const m=Math.floor(t/60),s=t-m*60;return`${m}:${s.toFixed(3).padStart(6,'0')}`}
function setRenderUi(text,button){const dot=$('#renderDot'),status=$('#renderState'),render=$('#render');if(dot)dot.classList.add('pending');if(status)status.textContent=text;if(render&&!state.rendering)render.textContent=button}
export function markDirty(){state.dirty=true;state.previewCurrent=false;state.dirtyRevision=(state.dirtyRevision||0)+1;setRenderUi('EDIT LIVE · AUDIO PREVIEW CATCHING UP','⚡ RENDER FINAL');if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('phase:render-dirty',{detail:{revision:state.dirtyRevision}}))}
export function markPreviewRendering(){if(!state.dirty)return;state.previewRendering=true;state.previewCurrent=false;setRenderUi('EDIT LIVE · RENDERING AUDIO PREVIEW','⚡ RENDER FINAL')}
export function markPreviewCurrent(){if(!state.dirty)return;state.previewRendering=false;state.previewCurrent=true;setRenderUi('AUDIO PREVIEW CURRENT · FINAL RENDER AVAILABLE','⚡ RENDER FINAL');if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('phase:preview-ready',{detail:{revision:state.dirtyRevision}}))}
export function markCurrent(){state.dirty=false;state.previewRendering=false;state.previewCurrent=true;const dot=$('#renderDot'),status=$('#renderState'),render=$('#render');if(dot)dot.classList.remove('pending');if(status)status.textContent='AUDIO CURRENT';if(render&&!state.rendering)render.textContent='⚡ RENDER CHANGES';if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('phase:render-current'))}
