import{state,$,markDirty}from'./state.js';
import{decodeFile,stopAudio}from'./audio.js';
import{trackHasDspEdits}from'./render.js';
import{STEM_TYPES,ensureStemState,loadedStems,setStemBuffer,clearStem,setUseStems,stemDurationCompatible}from'./stems.js';
import{createHttpStemProvider,normalizeProviderEndpoint}from'./stem-provider.js';

const ENDPOINT_KEY='echoverse.phase.stemEndpoint';
let selectedTrack=0,lastSourceNames=state.tracks.map(t=>t.file?.name||null),separation=null;
for(const t of state.tracks)ensureStemState(t);
const style=document.createElement('style');style.textContent=`
.stem-drawer{position:fixed;z-index:70;top:82px;right:12px;width:min(430px,calc(100vw - 24px));max-height:calc(100vh - 110px);overflow:auto;border:1px solid #2a3945;border-radius:8px;background:#0d1319;box-shadow:0 18px 50px rgba(0,0,0,.45);padding:10px;display:none}.stem-drawer.open{display:block}
.stem-head{display:flex;align-items:center;gap:6px;margin-bottom:8px}.stem-head strong{font:700 11px ui-monospace,monospace;letter-spacing:.08em;color:#dbe5ea}.stem-head .spacer{flex:1}.stem-close{height:25px}
.stem-tabs{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-bottom:8px}.stem-tabs .active{border-color:#66b5a8;background:#1d302d;color:#d8eee8}
.stem-mode{display:flex;align-items:center;gap:8px;padding:8px;border:1px solid #202d36;border-radius:6px;background:#10171d;margin-bottom:8px}.stem-mode .mode-copy{flex:1}.stem-mode .mode-title{font:700 10px ui-monospace,monospace;color:#c7d1d7}.stem-mode .mode-sub{font:8px ui-monospace,monospace;color:#75858f;margin-top:2px}
.stem-provider{padding:8px;border:1px solid #202d36;border-radius:6px;background:#10171d;margin-bottom:8px}.stem-provider-title{font:700 9px ui-monospace,monospace;color:#a9b6bd;margin-bottom:5px}.stem-provider-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:5px}.stem-provider input{height:27px;min-width:0;width:100%;border:1px solid #263542;border-radius:5px;background:#0b1116;color:#d4dde2;padding:0 7px;font:9px ui-monospace,monospace}.stem-provider-status{margin-top:5px;font:8px ui-monospace,monospace;color:#75858f;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.stem-progress{height:3px;margin-top:6px;border-radius:3px;background:#172129;overflow:hidden}.stem-progress>span{display:block;width:0;height:100%;background:#66b5a8;transition:width .12s linear}
.stem-slot{display:grid;grid-template-columns:62px minmax(0,1fr) auto auto auto;gap:5px;align-items:center;padding:7px 0;border-top:1px solid rgba(255,255,255,.045)}.stem-slot:first-of-type{border-top:0}.stem-name{font:700 9px ui-monospace,monospace;color:#9eabb4}.stem-file{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:8px ui-monospace,monospace;color:#71818b}.stem-slot.loaded .stem-name{color:#9fd2c9}.stem-slot.warn .stem-file{color:#d8c28f}.stem-level{grid-column:2 / -1;display:grid;grid-template-columns:minmax(0,1fr) 48px;gap:6px;align-items:center}.stem-level input{width:100%;accent-color:#66b5a8}.stem-db{font:8px ui-monospace,monospace;text-align:right;color:#8f9da6}.stem-mini{height:24px;padding:0 6px}.stem-mini.active{border-color:#c6a66b;background:#302919;color:#f1deb5}.stem-solo.active{border-color:#66b5a8;background:#1d302d;color:#d8eee8}.stem-foot{margin-top:8px;padding-top:8px;border-top:1px solid #202d36;font:8px/1.45 ui-monospace,monospace;color:#71818b}
@media(max-width:620px){.stem-drawer{top:112px;right:7px;width:calc(100vw - 14px);max-height:calc(100vh - 140px)}.stem-slot{grid-template-columns:54px minmax(0,1fr) auto auto auto}.stem-mini{padding-inline:5px;font-size:8px}}
`;
document.head.appendChild(style);

function track(){return state.tracks[selectedTrack]}
function fmtDb(v){const n=Number(v)||0;return`${n>=0?'+':''}${n.toFixed(1)} dB`}
function savedEndpoint(){try{return normalizeProviderEndpoint(localStorage.getItem(ENDPOINT_KEY)||'')}catch{return''}}
function saveEndpoint(value){const endpoint=normalizeProviderEndpoint(value);try{endpoint?localStorage.setItem(ENDPOINT_KEY,endpoint):localStorage.removeItem(ENDPOINT_KEY)}catch{}return endpoint}
function providerStatus(text,progress=null){const s=$('#stemProviderStatus'),bar=$('#stemProgressBar');if(s)s.textContent=text;if(bar&&Number.isFinite(progress))bar.style.width=`${Math.max(0,Math.min(1,progress))*100}%`}

function install(){
  if(!$('#stemsPanel')){const btn=document.createElement('button');btn.id='stemsPanel';btn.className='mode';btn.textContent='STEMS';btn.title='Open stem import, separation and mix controls';const anchor=$('#suggestPair')||$('#phraseNext')||$('#alignB');anchor?.after(btn);btn.onclick=()=>{$('#stemDrawer').classList.toggle('open');refresh()}}
  if($('#stemDrawer'))return;
  const d=document.createElement('div');d.id='stemDrawer';d.className='stem-drawer';d.innerHTML=`<div class="stem-head"><strong>STEM SOURCES</strong><span class="spacer"></span><button class="mini stem-close" id="stemClose">CLOSE</button></div><div class="stem-tabs"><button class="mode" id="stemTrack0">TRACK A</button><button class="mode" id="stemTrack1">TRACK B</button></div><div class="stem-mode"><div class="mode-copy"><div class="mode-title" id="stemModeTitle">ORIGINAL MIX</div><div class="mode-sub" id="stemModeSub">Load stems to enable stem playback.</div></div><button class="mode stem-mix-control" id="stemUse">USE STEMS</button></div><div class="stem-provider"><div class="stem-provider-title">OPTIONAL SEPARATION PROVIDER</div><div class="stem-provider-row"><input id="stemEndpoint" type="url" placeholder="https://separator.example" spellcheck="false"><button class="mode" id="stemSeparate">SEPARATE</button></div><div class="stem-provider-status" id="stemProviderStatus">NOT CONFIGURED · MANUAL LOAD REMAINS AVAILABLE</div><div class="stem-progress"><span id="stemProgressBar"></span></div></div><div id="stemSlots"></div><div class="stem-foot">Stems stay local in the editor. The original mix remains the analysis/grid authority. Loaded or separated stems inherit this track’s warp, pitch, placement, trim and fades. SOLO isolates one or more stems without changing the source files. Project maps remember filenames/settings, not audio bytes.</div>`;document.body.appendChild(d);
  $('#stemEndpoint').value=savedEndpoint();$('#stemEndpoint').onchange=()=>{const ep=saveEndpoint($('#stemEndpoint').value);$('#stemEndpoint').value=ep;providerStatus(ep?'PROVIDER SAVED · READY WHEN SOURCE AUDIO IS LOADED':'NOT CONFIGURED · MANUAL LOAD REMAINS AVAILABLE',0);refreshProviderButton()};
  $('#stemClose').onclick=()=>d.classList.remove('open');$('#stemTrack0').onclick=()=>{selectedTrack=0;refresh()};$('#stemTrack1').onclick=()=>{selectedTrack=1;refresh()};$('#stemUse').onclick=()=>{const t=track(),before=!!t.useStems,next=setUseStems(t,!before);if(next!==before&&trackHasDspEdits(t))markDirty();stopAudio();refresh();$('#engineState').textContent=`${t.label} SOURCE · ${next?'STEMS':'ORIGINAL MIX'}${trackHasDspEdits(t)?' · RENDER CHANGES TO APPLY TIMING':''}`};$('#stemSeparate').onclick=()=>{if(separation){separation.controller.abort();return}separateTrack()};
}

async function loadStem(id,file){const t=track();$('#engineState').textContent=`DECODING ${t.label} ${id.toUpperCase()}…`;try{const buffer=await decodeFile(file),compatible=stemDurationCompatible(t,buffer);setStemBuffer(t,id,buffer,{fileName:file.name,durationWarning:!compatible});if(t.useStems&&trackHasDspEdits(t))markDirty();refresh();$('#engineState').textContent=`${t.label} ${id.toUpperCase()} LOADED · ${buffer.duration.toFixed(2)}s${compatible?'':' · CHECK DURATION'}`}catch(err){console.error(err);$('#engineState').textContent='STEM DECODE FAILED';alert('Could not decode stem: '+(err.message||err))}}

function refreshProviderButton(){const t=track(),ep=normalizeProviderEndpoint($('#stemEndpoint')?.value||savedEndpoint()),btn=$('#stemSeparate');if(!btn)return;btn.disabled=!separation&&(!ep||!t.file);btn.textContent=separation?'■ CANCEL':'SEPARATE';btn.title=!ep?'Configure a stem provider endpoint first':!t.file?'Reload the original source file before automatic separation':'Send this original source to the configured stem provider'}
async function separateTrack(){
  const t=track(),endpoint=saveEndpoint($('#stemEndpoint')?.value||savedEndpoint());if(!endpoint||!t.file)return refreshProviderButton();const controller=new AbortController(),trackId=t.id;separation={controller,trackId};refreshProviderButton();providerStatus(`UPLOADING ${t.label}…`,0);$('#engineState').textContent=`STEM SEPARATION · ${t.label} · UPLOADING…`;
  try{
    const provider=createHttpStemProvider({endpoint}),result=await provider.separate({file:t.file,trackLabel:t.label,signal:controller.signal,onProgress:p=>{const pct=Math.round((p.progress||0)*100),stage=String(p.stage||'running').toUpperCase();providerStatus(`${stage} · ${pct}%${p.stem?` · ${String(p.stem).toUpperCase()}`:''}`,p.progress);$('#engineState').textContent=`STEM SEPARATION · ${t.label} · ${stage} ${pct}%`}});
    let count=0,warnings=0;for(const id of STEM_TYPES){const item=result.stems[id];if(!item)continue;const file=new File([item.blob],item.fileName||`${id}.wav`,{type:item.type||item.blob.type||'audio/wav'}),buffer=await decodeFile(file),compatible=stemDurationCompatible(t,buffer);setStemBuffer(t,id,buffer,{fileName:file.name,durationWarning:!compatible});count++;if(!compatible)warnings++}
    setUseStems(t,true);if(trackHasDspEdits(t))markDirty();stopAudio();providerStatus(`COMPLETE · ${count} STEM${count===1?'':'S'}${warnings?` · ${warnings} DURATION WARNING${warnings===1?'':'S'}`:''}`,1);$('#engineState').textContent=`${t.label} STEMS READY · ${count} LOADED${trackHasDspEdits(t)?' · RENDER CHANGES TO APPLY TIMING':''}`;
  }catch(err){if(err?.name==='AbortError'){providerStatus('CANCELLED · MANUAL LOAD REMAINS AVAILABLE',0);$('#engineState').textContent='STEM SEPARATION CANCELLED'}else{console.error(err);providerStatus(`FAILED · ${err.message||err}`,0);$('#engineState').textContent='STEM SEPARATION FAILED';alert('Stem separation failed: '+(err.message||err))}}
  finally{separation=null;refresh()}
}

function buildSlots(){
  const t=track(),host=$('#stemSlots');host.innerHTML='';
  for(const id of STEM_TYPES){
    const s=t.stems[id],row=document.createElement('div');row.className='stem-slot'+(s.buffer?' loaded':'')+(s.durationWarning?' warn':'');
    row.innerHTML=`<span class="stem-name">${s.label}</span><span class="stem-file" title="${s.fileName||''}">${s.fileName||'NOT LOADED'}</span><button class="mini stem-mini" data-load>LOAD</button><button class="mini stem-mini stem-mute stem-mix-control${s.mute?' active':''}" data-mute>${s.mute?'MUTED':'MUTE'}</button><button class="mini stem-mini stem-solo stem-mix-control${s.solo?' active':''}" data-solo>${s.solo?'SOLOED':'SOLO'}</button><div class="stem-level"><input class="stem-gain stem-mix-control" data-gain type="range" min="-24" max="12" step="0.5" value="${s.gainDb}"><span class="stem-db">${fmtDb(s.gainDb)}</span></div><input hidden data-file type="file" accept="audio/*">`;
    host.appendChild(row);const file=row.querySelector('[data-file]');row.querySelector('[data-load]').onclick=()=>file.click();file.onchange=e=>e.target.files[0]&&loadStem(id,e.target.files[0]);
    row.querySelector('[data-mute]').onclick=()=>{s.mute=!s.mute;if(s.mute)s.solo=false;stopAudio();refresh();$('#engineState').textContent=`${t.label} ${s.label} ${s.mute?'MUTED':'ACTIVE'}`};
    row.querySelector('[data-solo]').onclick=()=>{s.solo=!s.solo;if(s.solo)s.mute=false;stopAudio();refresh();const count=loadedStems(t).filter(x=>x.solo&&!x.mute).length;$('#engineState').textContent=count?`${t.label} STEM SOLO · ${count} ISOLATED`:`${t.label} STEM SOLO CLEARED`};
    const gain=row.querySelector('[data-gain]');gain.oninput=()=>{s.gainDb=+gain.value;row.querySelector('.stem-db').textContent=fmtDb(s.gainDb);$('#engineState').textContent=`${t.label} ${s.label} · ${fmtDb(s.gainDb)}`};
    row.querySelector('.stem-file').ondblclick=()=>{if(!s.buffer)return;clearStem(t,id);if(!loadedStems(t).length)t.useStems=false;stopAudio();refresh();$('#engineState').textContent=`${t.label} ${id.toUpperCase()} CLEARED`};
  }
}
function refresh(){install();for(const t of state.tracks)ensureStemState(t);const t=track(),loaded=loadedStems(t),soloCount=loaded.filter(s=>s.solo&&!s.mute).length;$('#stemTrack0').classList.toggle('active',selectedTrack===0);$('#stemTrack1').classList.toggle('active',selectedTrack===1);$('#stemUse').disabled=!loaded.length;$('#stemUse').classList.toggle('active',t.useStems);$('#stemUse').textContent=t.useStems?'USING STEMS':'USE STEMS';$('#stemModeTitle').textContent=t.useStems?`${loaded.length} STEM${loaded.length===1?'':'S'} ACTIVE`:'ORIGINAL MIX';$('#stemModeSub').textContent=loaded.length?`${loaded.length}/4 loaded · ${t.useStems?'stem sources feed playback/export':'original mix feeds playback/export'}${soloCount?` · ${soloCount} solo`:''}`:'Load one or more stems to enable stem playback.';const total=state.tracks.reduce((n,x)=>n+loadedStems(x).length,0),b=$('#stemsPanel');if(b)b.textContent=total?`STEMS ${total}`:'STEMS';buildSlots();refreshProviderButton()}
setInterval(()=>{state.tracks.forEach((t,i)=>{const name=t.file?.name||null;if(name!==lastSourceNames[i]){if(lastSourceNames[i]&&name){for(const id of STEM_TYPES)clearStem(t,id);t.useStems=false}lastSourceNames[i]=name}})},400);
window.addEventListener('phase:project-applied',()=>setTimeout(refresh,0));window.addEventListener('phase:history-applied',()=>setTimeout(refresh,0));window.addEventListener('keydown',e=>{if(e.code==='Escape'&&$('#stemDrawer')?.classList.contains('open')){if(separation)separation.controller.abort();else $('#stemDrawer').classList.remove('open')}});
install();refresh();
