import{state,$}from'./state.js';
import{createSupportSnapshot,supportSummary}from'./support-snapshot.js';
import{readRuntimeLog}from'./runtime-guard.js';

function appVersion(){return($('.brand .tag')?.textContent||'').replace(/ALPHA/gi,'').trim()}
async function environment(){const env={version:appVersion(),serviceWorker:'serviceWorker'in navigator,worker:!!window.Worker,webAudio:!!(window.AudioContext||window.webkitAudioContext),offlineAudio:!!window.OfflineAudioContext};try{const r=await fetch(`./build.json?ts=${Date.now()}`,{cache:'no-store'});if(r.ok){const b=await r.json();env.deployedVersion=b.version||null;env.deployedCommit=b.commit||null;env.deployedBuiltAt=b.builtAt||null}}catch{}return env}
function saveJson(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)}
async function download(redacted=false){const button=$(redacted?'#supportRedacted':'#supportSnapshot');if(button){button.disabled=true;button.textContent='BUILDING…'}try{const snapshot=createSupportSnapshot(state,{environment:await environment(),runtimeEvents:readRuntimeLog(),includeFileNames:!redacted}),summary=supportSummary(snapshot);saveJson(snapshot,redacted?'phase-support-redacted.json':'phase-support.json');$('#engineState').textContent=`SUPPORT SNAPSHOT SAVED · ${summary.warnings} WARNING${summary.warnings===1?'':'S'} · NO AUDIO BYTES${redacted?' · FILENAMES REDACTED':''}`}catch(err){console.error(err);$('#engineState').textContent='SUPPORT SNAPSHOT FAILED'}finally{if(button){button.disabled=false;button.textContent=redacted?'REDACTED SNAPSHOT':'SUPPORT SNAPSHOT'}}}
function install(){const actions=document.querySelector('.diag-actions');if(!actions||$('#supportSnapshot'))return;const a=document.createElement('button'),b=document.createElement('button');a.className=b.className='mode';a.id='supportSnapshot';b.id='supportRedacted';a.textContent='SUPPORT SNAPSHOT';b.textContent='REDACTED SNAPSHOT';a.title='Download diagnostics, runtime history and project edit metadata. Audio bytes are never included.';b.title='Same support snapshot with source/stem filenames redacted.';a.onclick=()=>download(false);b.onclick=()=>download(true);const anchor=$('#diagDownload');anchor?.after(a,b)}
install();window.addEventListener('phase:optional-ui-ready',install);setTimeout(install,0);
