const CACHE='echoverse-phase-shell-v41';
const BASE=self.registration.scope;
const asset=path=>new URL(path,BASE).href;
const CORE=['./','./recovery.html','./styles.css','./ui-polish.css','./manifest.webmanifest','./icons/phase.svg','./js/state.js','./js/audio.js','./js/analysis.js','./js/warp.js','./js/arrangement.js','./js/region-model.js','./js/fade-model.js','./js/tempo-model.js','./js/phrase-model.js','./js/compatibility.js','./js/source-identity.js','./js/stems.js','./js/source-model.js','./js/stem-render.js','./js/stem-provider.js','./js/diagnostics.js','./js/runtime-guard.js','./js/session-safety.js','./js/resource-preflight.js','./js/resource-preflight-ui.js','./js/project-package.js','./js/support-snapshot.js','./js/demo-audio.js','./js/render-quality.js','./js/render-core.js','./js/render-worker.js','./js/render.js','./js/export.js','./js/app.js','./js/arrange-ui.js','./js/mix-ui.js','./js/project-model.js','./js/project-ui.js','./js/history-ui.js','./js/visual-guides.js','./js/transport-model.js','./js/transport-ui.js','./js/export-loop-ui.js','./js/trim-ui.js','./js/region-ui.js','./js/fade-ui.js','./js/render-quality-ui.js','./js/meter-ui.js','./js/tempo-ui.js','./js/phrase-ui.js','./js/compatibility-ui.js','./js/stems-ui.js','./js/diagnostics-ui.js','./js/support-ui.js','./js/help-ui.js','./js/accessibility-ui.js','./js/demo-ui.js','./js/optional-ui.js'].map(asset);
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
async function cached(request){return caches.match(request,{ignoreSearch:true})}
async function networkFirst(request){try{const response=await fetch(request,{cache:'no-store'});if(response&&response.ok&&new URL(request.url).origin===self.location.origin){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy))}return response}catch{return(await cached(request))||(request.mode==='navigate'?await cached(asset('./')):Response.error())}}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url),dest=event.request.destination,dynamic=event.request.mode==='navigate'||dest==='script'||dest==='style'||url.pathname.endsWith('.js')||url.pathname.endsWith('.css')||url.pathname.endsWith('.html')||url.pathname.endsWith('/build.json');if(dynamic){event.respondWith(networkFirst(event.request));return}event.respondWith(cached(event.request).then(hit=>hit||networkFirst(event.request)))});
