import test from'node:test';import assert from'node:assert/strict';
import{audioBufferBytes,trackAudioMemoryBytes,markerGridIssues,trackDiagnostics,projectDiagnostics,diagnosticSeverity,performanceProfile}from'../js/diagnostics.js';

const audio=(duration=10,sampleRate=44100,channels=2)=>({duration,sampleRate,numberOfChannels:channels,length:Math.round(duration*sampleRate)});
const track=()=>({id:0,label:'TRACK A',file:{name:'a.wav'},buffer:audio(),duration:10,sourceBpm:100,meter:'4/4',gridMode:'detected',markers:[{sourceTime:0,targetTime:0},{sourceTime:.6,targetTime:.6}],analysis:{bpm:100,meter:'4/4',key:'Am',tempoConfidence:.8,meterConfidence:.7,downbeatConfidence:.6,keyConfidence:.9},timelineOffset:0,renderedOffset:0,gainDb:0,stems:{}});

test('audio buffer bytes uses float32 channel storage',()=>assert.equal(audioBufferBytes(audio(1,48000,2)),48000*2*4));
test('track memory counts unique source rendered and stem buffers',()=>{const t=track(),rendered=audio(10),stem=audio(5);t.renderedBuffer=rendered;t.stems={vocals:{buffer:stem,renderedBuffer:stem}};assert.equal(trackAudioMemoryBytes(t),audioBufferBytes(t.buffer)+audioBufferBytes(rendered)+audioBufferBytes(stem))});
test('healthy marker grid has no diagnostic issues',()=>assert.deepEqual(markerGridIssues(track()),[]));
test('diagnostics catch non-increasing target time',()=>{const t=track();t.markers[1].targetTime=0;assert.deepEqual(markerGridIssues(t),['TARGET_TIME_NOT_INCREASING@2'])});
test('track diagnostics summarize audio analysis memory and warnings',()=>{const t=track(),d=trackDiagnostics(t);assert.equal(d.loaded,true);assert.equal(d.fileName,'a.wav');assert.equal(d.sampleRate,44100);assert.equal(d.analysis.key,'Am');assert.equal(d.memoryBytes,audioBufferBytes(t.buffer));assert.deepEqual(d.warnings,[])});
test('project diagnostics distinguishes preview current from final render pending',()=>{const s={bpm:100,meter:'4/4',dirty:true,previewCurrent:true,previewRendering:false,rendering:false,playing:false,viewDuration:60,pxPerSecond:8,tracks:[track()]},r=projectDiagnostics(s,{version:'0.13.0',serviceWorker:true,worker:true,webAudio:true,offlineAudio:true,sessionSaved:true,localStorageWritable:true});assert.equal(r.healthy,false);assert.ok(r.warnings.includes('FINAL_RENDER_PENDING'));assert.equal(r.project.previewCurrent,true);assert.equal(r.project.previewRendering,false);assert.ok(r.project.audioMemoryBytes>0);assert.equal(diagnosticSeverity(r),'warning')});
test('project diagnostics reports active preview rendering separately from final rendering',()=>{const r=projectDiagnostics({dirty:true,previewCurrent:false,previewRendering:true,rendering:false,tracks:[]},{serviceWorker:true,worker:true,webAudio:true,offlineAudio:true});assert.equal(r.project.previewRendering,true);assert.equal(r.project.rendering,false);assert.ok(r.warnings.includes('FINAL_RENDER_PENDING'));assert.equal(r.warnings.includes('FINAL_RENDER_IN_PROGRESS'),false)});
test('project diagnostics warns when resident decoded audio crosses configured caution threshold',()=>{const t=track(),s={tracks:[t]},threshold=1024;const r=projectDiagnostics(s,{serviceWorker:true,worker:true,webAudio:true,offlineAudio:true,audioMemoryWarnBytes:threshold,sessionSaved:true,localStorageWritable:true});assert.ok(r.warnings.includes('AUDIO_MEMORY_HIGH'));assert.equal(diagnosticSeverity(r),'warning')});
test('deployed version mismatch reports app update available',()=>{const r=projectDiagnostics({tracks:[]},{version:'0.13.0',deployedVersion:'0.13.1',serviceWorker:true,worker:true,webAudio:true,offlineAudio:true});assert.ok(r.warnings.includes('APP_UPDATE_AVAILABLE'));assert.equal(diagnosticSeverity(r),'warning')});
test('matching deployed version does not report an update',()=>{const r=projectDiagnostics({tracks:[]},{version:'0.13.0',deployedVersion:'0.13.0',serviceWorker:true,worker:true,webAudio:true,offlineAudio:true});assert.equal(r.warnings.includes('APP_UPDATE_AVAILABLE'),false)});
test('loaded project warns when the session map is not saved',()=>{const r=projectDiagnostics({tracks:[track()]},{serviceWorker:true,worker:true,webAudio:true,offlineAudio:true,localStorageWritable:true,sessionSaved:false});assert.ok(r.warnings.includes('SESSION_MAP_NOT_SAVED'));assert.equal(diagnosticSeverity(r),'warning')});
test('local storage failure is error severity when a project is loaded',()=>{const r=projectDiagnostics({tracks:[track()]},{serviceWorker:true,worker:true,webAudio:true,offlineAudio:true,localStorageWritable:false,sessionSaved:false});assert.ok(r.warnings.includes('LOCAL_STORAGE_UNAVAILABLE'));assert.equal(diagnosticSeverity(r),'error')});
test('large saved project map is surfaced as a warning',()=>{const r=projectDiagnostics({tracks:[]},{serviceWorker:true,worker:true,webAudio:true,offlineAudio:true,sessionBytes:2*1024*1024+1});assert.ok(r.warnings.includes('SESSION_MAP_LARGE'));assert.equal(diagnosticSeverity(r),'warning')});
test('missing required browser engine is error severity',()=>{const r=projectDiagnostics({tracks:[]},{serviceWorker:true,worker:false,webAudio:true,offlineAudio:true});assert.equal(diagnosticSeverity(r),'error');assert.ok(r.warnings.includes('WEB_WORKER_UNAVAILABLE'))});

test('performance profile reports ready startup and memory headroom',()=>{const p=performanceProfile({navigationTiming:{domInteractiveMs:800},bootTiming:{runtimeReadyMs:1400,optionalRequestedMs:900,optionalReadyMs:1300}},{audioMemoryBytes:128*1024*1024,memoryWarnBytes:512*1024*1024});assert.equal(p.status,'ready');assert.equal(p.score,100);assert.ok(p.signals.every(s=>s.status==='ready'))});
test('performance profile surfaces runtime pressure without failing diagnostics capability checks',()=>{const p=performanceProfile({navigationTiming:{domInteractiveMs:3600},bootTiming:{runtimeReadyMs:6200,optionalRequestedMs:500,optionalReadyMs:3600}},{audioMemoryBytes:700*1024*1024,memoryWarnBytes:512*1024*1024});assert.equal(p.status,'pressure');assert.ok(p.score<50);assert.ok(p.signals.some(s=>s.id==='AUDIO_MEMORY_RATIO'&&s.status==='pressure'))});
