import test from'node:test';import assert from'node:assert/strict';
import{snapshotProject,applyProjectSnapshot,applyTrackSnapshot,editableFingerprint,validateProject}from'../js/project-model.js';

const sourceFile={name:'a.wav',size:1000,lastModified:123,type:'audio/wav'};
const makeState=()=>({bpm:98,meterPreference:'auto',meter:'3/4',beatsPerBar:3,viewDuration:180,pxPerSecond:12,snapMode:'16bar',playheadTime:42.5,loopBars:16,loopEnabled:true,regionStart:32,regionEnd:64,tracks:[{label:'TRACK A',name:'a.wav',file:{...sourceFile},buffer:{},sourceBpm:97.5,pitch:0,timelineOffset:1.25,meterPreference:'auto',meter:'3/4',beatsPerBar:3,trimIn:3.5,trimOut:91.25,fadeInStart:2,fadeInEnd:6,fadeOutStart:80,fadeOutEnd:84,gridMode:'detected',alignMarker:8,gainDb:-2.5,mute:false,solo:true,useStems:true,stems:{vocals:{buffer:{duration:100},fileName:'vocals.wav',identity:{name:'vocals.wav',size:500,lastModified:555,type:'audio/wav'},gainDb:-1,mute:false,solo:true},drums:{buffer:{duration:100},fileName:'drums.wav',identity:{name:'drums.wav',size:800,lastModified:666,type:'audio/wav'},gainDb:0,mute:true}},analysis:{bpm:97.5,rawBpm:195,tempoOctaveAdjusted:true,tempoConfidence:.7,meter:'3/4',beatsPerBar:3,meterConfidence:.66,downbeatPhase:0,downbeatConfidence:.7,key:'Am',keyRoot:9,keyMode:'minor',keyConfidence:.8},markers:[{beat:0,sourceTime:0,targetTime:0,downbeat:true,locked:true,confidence:1},{beat:1,sourceTime:.6,targetTime:.62,downbeat:false,locked:false,confidence:.5}]}]});

test('Phase project snapshots preserve arrangement, source identities, stems and mix metadata',()=>{const p=snapshotProject(makeState());assert.equal(p.version,12);assert.equal(p.meter,'3/4');assert.equal(p.beatsPerBar,3);assert.equal(p.snapMode,'16bar');assert.equal(p.playheadTime,42.5);assert.equal(p.loopBars,16);assert.equal(p.loopEnabled,true);assert.equal(p.regionStart,32);assert.equal(p.regionEnd,64);assert.equal(p.tracks[0].fileName,'a.wav');assert.equal(p.tracks[0].fileIdentity.size,1000);assert.equal(p.tracks[0].fileIdentity.lastModified,123);assert.equal(p.tracks[0].meter,'3/4');assert.equal(p.tracks[0].alignMarker,8);assert.equal(p.tracks[0].trimIn,3.5);assert.equal(p.tracks[0].fadeOutEnd,84);assert.equal(p.tracks[0].gainDb,-2.5);assert.equal(p.tracks[0].useStems,true);assert.equal(p.tracks[0].stems.vocals.fileName,'vocals.wav');assert.equal(p.tracks[0].stems.vocals.identity.size,500);assert.equal(p.tracks[0].stems.vocals.solo,true);assert.equal(p.tracks[0].stems.drums.mute,true);assert.equal('buffer'in p.tracks[0].stems.vocals,false);assert.equal(p.tracks[0].analysis.key,'Am');assert.equal(p.tracks[0].markers[1].targetTime,.62)});

test('project snapshot applies arrangement without replacing loaded audio identity',()=>{const source=snapshotProject(makeState()),target=makeState(),audio=target.tracks[0].buffer;target.bpm=120;target.meter='4/4';target.beatsPerBar=4;target.playheadTime=0;target.loopEnabled=false;target.regionStart=null;target.regionEnd=null;target.tracks[0].timelineOffset=0;target.tracks[0].trimIn=0;target.tracks[0].trimOut=null;target.tracks[0].fadeInStart=null;target.tracks[0].fadeInEnd=null;target.tracks[0].markers[1].targetTime=.6;applyProjectSnapshot(target,source,{loadedOnly:true});assert.equal(target.bpm,98);assert.equal(target.meter,'3/4');assert.equal(target.playheadTime,42.5);assert.equal(target.loopEnabled,true);assert.equal(target.regionStart,32);assert.equal(target.tracks[0].timelineOffset,1.25);assert.equal(target.tracks[0].trimIn,3.5);assert.equal(target.tracks[0].fadeOutEnd,84);assert.equal(target.tracks[0].stems.vocals.fileName,'vocals.wav');assert.equal(target.tracks[0].fileIdentity.size,1000);assert.equal(target.tracks[0].markers[1].targetTime,.62);assert.equal(target.tracks[0].buffer,audio)});

test('unloaded tracks defer marker restoration and retain source/stem relink metadata',()=>{const src=snapshotProject(makeState()).tracks[0],track={label:'TRACK A',buffer:null,markers:[{beat:0,sourceTime:0,targetTime:0}],sourceBpm:120,pitch:0,timelineOffset:0};applyTrackSnapshot(track,src,{applyMarkers:false});assert.equal(track.timelineOffset,1.25);assert.equal(track.meter,'3/4');assert.equal(track.trimIn,3.5);assert.equal(track.markers.length,1);assert.equal(track.fileName,'a.wav');assert.equal(track.fileIdentity.size,1000);assert.equal(track.stems.vocals.fileName,'vocals.wav');assert.equal(track.stems.vocals.identity.size,500);assert.equal(track.useStems,false)});

test('editable fingerprint ignores source identity and analysis but tracks stem mix state',()=>{const a=makeState(),b=makeState();b.tracks[0].file={name:'renamed.wav',size:999,lastModified:999,type:'audio/wav'};b.tracks[0].analysis.key='C';b.tracks[0].stems.vocals.fileName='renamed-vocals.wav';b.tracks[0].stems.vocals.identity={name:'renamed-vocals.wav',size:999};assert.equal(editableFingerprint(a),editableFingerprint(b));b.tracks[0].stems.vocals.gainDb=-4;assert.notEqual(editableFingerprint(a),editableFingerprint(b));b.tracks[0].stems.vocals.gainDb=-1;b.meter='4/4';b.beatsPerBar=4;assert.notEqual(editableFingerprint(a),editableFingerprint(b))});

test('validation rejects non Phase maps',()=>assert.throws(()=>validateProject({app:'other',tracks:[]})));
